Diluc = {
    "Name": "Diluc",
    "Lv": 80,
    "BHP": 12068,
    "BATK": 311,
    "BDEF": 729,
    "CRATE": 24.2,
    "CDMG": 50,
    "EM": 0,
    "PYRO_DMG": 0,
    "CRYO_DMG": 0,
    "HYDRO_DMG": 0,
    "GEO_DMG": 0,
    "ELEC_DMG": 0,
    "ANEMO_DMG": 0,
    "ELE_DMG": 0,
    "PHYS_DMG": 0, 
    "REACT_DMG": 0,
    "ER": 100,
    "ATK_PER_10s": 14,
}

Kaeya = {
    "Name": "Kaeya",
    "Lv": 80,
    "BHP": 10830,
    "BATK": 208,
    "BDEF": 737,
    "CRATE": 5,
    "CDMG": 50,
    "EM": 0,
    "PYRO_DMG": 0,
    "CRYO_DMG": 0,
    "HYDRO_DMG": 0,
    "GEO_DMG": 0,
    "ELEC_DMG": 0,
    "ANEMO_DMG": 0,
    "ELE_DMG": 0,
    "PHYS_DMG": 0, 
    "REACT_DMG": 0,
    "ER": 126.7,
    "ATK_PER_10s": 16,
}